/// <reference lib="deno.ns" />
/**
 * Seedream (BytePlus ModelArk) image-generation client.
 *
 * Seedream is Bytedance's image model family served through the same
 * BytePlus "Ark" inference API as Seedance. Unlike Seedance video,
 * image generation is synchronous — one POST returns the rendered
 * image URL directly, no submit/poll loop needed.
 *
 * Endpoint: `${ARK_BASE}/api/v3/images/generations`
 * Auth:     `Authorization: Bearer $ARK_API_KEY`
 *
 * Body shape mirrors the OpenAI Images API spec that BytePlus
 * intentionally implements for drop-in compatibility:
 *   {
 *     "model": "seedream-5-0-260128",
 *     "prompt": "...",
 *     "size":  "1024x1024",
 *     "response_format": "url"
 *   }
 *
 * Response:
 *   { "data": [ { "url": "https://..." } ], "usage": {...} }
 *
 * Reuses the same SEEDANCE_API_KEY env var (BytePlus issues one Ark
 * key per account that grants access to all Seedance + Seedream
 * models). The credential loader is shared via _shared/seedance.ts.
 */

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { loadSeedanceCredentials } from "./seedance.ts";
import type { ProviderResult } from "./providerResult.ts";

/** BytePlus ModelArk base URL (international). Same gateway as Seedance. */
export const SEEDREAM_BASE = "https://ark.ap-southeast.bytepluses.com";
export const SEEDREAM_IMAGES_PATH = "/api/v3/images/generations";

/** Map UI model slug → Ark model ID + capability flags. */
export interface SeedreamModelEntry {
  /** Ark model ID — the value sent in the API `model` field. */
  model: string;
  /** Pricing/quality tier label. Used for logging only. */
  tier: "v4" | "v5" | "v5-lite";
  /** Maximum supported size string the model accepts. */
  maxSize: string;
}

export const SEEDREAM_MODEL_MAP: Record<string, SeedreamModelEntry> = {
  // BytePlus ModelArk Seedream 5.0 — verified in ap-southeast-1
  // console on 2026-04-30. Pricing row in credit_costs uses the
  // verbatim BytePlus ID as the `model` column.
  "seedream-5-0":          { model: "seedream-5-0-260128", tier: "v5", maxSize: "2048x2048" },
  "seedream-5-0-260128":   { model: "seedream-5-0-260128", tier: "v5", maxSize: "2048x2048" },
  "seedream-5":            { model: "seedream-5-0-260128", tier: "v5", maxSize: "2048x2048" },
  "seedream-5-0-lite-260128": { model: "seedream-5-0-lite-260128", tier: "v5-lite", maxSize: "2048x2048" },
  "seedream-4-5-251128":   { model: "seedream-4-5-251128", tier: "v4", maxSize: "2048x2048" },
};

export interface SeedreamGenerateRequest {
  /** Ark model ID. */
  model: string;
  /** Text prompt. */
  prompt: string;
  /** Image size — "WIDTHxHEIGHT" (e.g. "1024x1024", "1024x1792"). */
  size?: string;
  /** "url" returns hosted URL, "b64_json" returns inline base64. */
  response_format?: "url" | "b64_json";
  /** Optional seed for reproducibility. */
  seed?: number;
  /** Image-EDIT mode (single ref). When set, BytePlus Seedream 4.5 +
   *  5.0 treat this URL as the canonical input and preserve subject
   *  + composition, even with a short prompt. Use this for the
   *  dominant canvas case: one wired ref_image edge or one
   *  @-mention. ≤10 MB, jpg/png/webp/bmp/tiff/gif. */
  image?: string;
  /** Style/mood BLEND mode (multi-ref). When set with an array of
   *  URLs, the model draws loose inspiration only; subject and
   *  composition are NOT preserved. Use for multi-ref blending
   *  scenarios; with a single URL prefer `image` instead. Max 14
   *  refs, same per-file constraints as `image`. */
  image_urls?: string[];
  /** Optional negative prompt — Seedream supports it on most variants. */
  negative_prompt?: string;
  /** Number of images to return. BytePlus tops out at ~4. */
  n?: number;
  /** BytePlus stamps a "Generated by AI" logo on the output unless this
   *  is explicitly false. The published docs claim the default is
   *  `false`, but the international Ark endpoint
   *  (ark.ap-southeast.bytepluses.com) ships images with the watermark
   *  on every Seedream call when this field is omitted — verified
   *  2026-05-14 against seedream-5-0-260128. We send `false`
   *  unconditionally; the workspace UI no longer exposes a toggle since
   *  no creator-facing flow benefits from a watermarked output. */
  watermark?: boolean;
}

export interface SeedreamImageItem {
  /** When response_format=url. */
  url?: string;
  /** When response_format=b64_json. */
  b64_json?: string;
  /** Per-image revised prompt the model actually rendered (occasionally returned). */
  revised_prompt?: string;
}

export interface SeedreamGenerateResponse {
  /** Unix seconds, when the API returns it. */
  created?: number;
  data?: SeedreamImageItem[];
  /** Token / image counters when returned. */
  usage?: { generated_images?: number; total_tokens?: number };
  /** Present only on error. */
  error?: { code?: string; message?: string };
}

/**
 * One-shot Seedream image generation. Throws on non-2xx, on missing
 * `data[0].url`, or on the BytePlus-specific billing/quota signals so
 * the executor can surface a clean error to the user.
 */
export async function generateSeedreamImage(
  body: SeedreamGenerateRequest,
  apiKey: string,
): Promise<SeedreamImageItem[]> {
  const url = `${SEEDREAM_BASE}${SEEDREAM_IMAGES_PATH}`;
  console.log(`[seedream] POST ${url} model=${body.model} size=${body.size ?? "default"}`);

  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify(body),
  });

  const text = await res.text();
  if (!res.ok) {
    console.error(`[seedream] HTTP ${res.status}: ${text.substring(0, 500)}`);
    if (
      res.status === 402 ||
      (res.status !== 429 &&
        /account balance not enough|insufficient balance|insufficient_quota|billing|payment required|prepaid|top[ -]?up|quota exceeded/i.test(text))
    ) {
      throw new Error("PROVIDER_BILLING_ERROR");
    }
    if (res.status === 401 || res.status === 403) {
      throw new Error(
        `Seedream authentication failed (HTTP ${res.status}) — check SEEDANCE_API_KEY ` +
          `(same BytePlus ModelArk key powers Seedance + Seedream).`,
      );
    }
    throw new Error(
      `Seedream API error (HTTP ${res.status}): ${text.substring(0, 200)}`,
    );
  }

  let parsed: SeedreamGenerateResponse;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error(`Seedream returned non-JSON response: ${text.substring(0, 200)}`);
  }

  if (!Array.isArray(parsed.data) || parsed.data.length === 0) {
    const errMsg = parsed.error?.message ?? "no data in response";
    throw new Error(`Seedream generation failed: ${errMsg}`);
  }

  return parsed.data;
}

/** Convenience wrapper that loads creds + extracts the first image URL. */
export async function generateSeedreamSingleUrl(
  body: SeedreamGenerateRequest,
): Promise<{ url: string; raw: SeedreamImageItem[] }> {
  const { apiKey } = loadSeedanceCredentials();
  const items = await generateSeedreamImage(
    { ...body, response_format: body.response_format ?? "url", n: body.n ?? 1 },
    apiKey,
  );
  const first = items[0];
  const url = first?.url;
  if (!url) {
    throw new Error("Seedream returned no URL in the first image item.");
  }
  return { url, raw: items };
}

export async function executeSeedream(
  params: Record<string, unknown>,
  supabase: ReturnType<typeof createClient>,
): Promise<ProviderResult> {
  const { apiKey } = loadSeedanceCredentials();

  const modelSlug = String(params.model_name ?? params.model ?? "seedream-5-0");
  const entry = SEEDREAM_MODEL_MAP[modelSlug];
  if (!entry) {
    throw new Error(
      `Unknown Seedream model: ${modelSlug}. ` +
        `Available: ${Object.keys(SEEDREAM_MODEL_MAP).join(", ")}`,
    );
  }

  const prompt = String(params.prompt ?? "").trim();
  if (!prompt) {
    throw new Error("Seedream requires a prompt.");
  }

  // Size — accept either an explicit "WxH" string or a {width,height}
  // pair the schema sometimes hands us. When the workspace passes an
  // aspect_ratio (e.g. "16:9") alongside a "2K"/"3K" tier, fold them
  // together into BytePlus-compatible pixel dimensions. 1:1 stays at
  // the doc-verified baselines 2048×2048 / 3072×3072; other ratios use
  // the same baseline pixel budget so the result lands inside the
  // BytePlus 3,686,400-10,404,496 total-pixel range (doc 1824121).
  const sizeRaw = params.size ?? params.image_size;
  const aspectRaw = params.aspect_ratio;
  const aspectMatch =
    typeof aspectRaw === "string" ? aspectRaw.match(/^(\d+)\s*:\s*(\d+)$/) : null;
  const tier =
    typeof sizeRaw === "string" && sizeRaw.toLowerCase() === "3k"
      ? "3K"
      : typeof sizeRaw === "string" && sizeRaw.toLowerCase() === "2k"
        ? "2K"
        : undefined;

  let size: string | undefined;
  if (typeof sizeRaw === "string" && /^\d+x\d+$/i.test(sizeRaw)) {
    size = sizeRaw;
  } else if (aspectMatch && tier) {
    const w = Number(aspectMatch[1]);
    const h = Number(aspectMatch[2]);
    const baseline = tier === "3K" ? 3072 : 2048;
    const target = baseline * baseline;
    const scale = Math.sqrt(target / (w * h));
    const round16 = (n: number) => Math.max(16, Math.round(n / 16) * 16);
    let width = round16(w * scale);
    let height = round16(h * scale);
    const MIN_PIXELS = 3_686_400;
    const MAX_PIXELS = 10_404_496;
    const total = width * height;
    if (total < MIN_PIXELS || total > MAX_PIXELS) {
      const clamp = Math.sqrt((total < MIN_PIXELS ? MIN_PIXELS : MAX_PIXELS) / total);
      width = round16(width * clamp);
      height = round16(height * clamp);
    }
    size = `${width}x${height}`;
  } else if (tier) {
    size = tier === "3K" ? "3072x3072" : "2048x2048";
  } else if (typeof params.width === "number" && typeof params.height === "number") {
    size = `${params.width}x${params.height}`;
  } else {
    size = "1024x1024";
  }

  const seedRaw = params.seed;
  const seed =
    typeof seedRaw === "number"
      ? seedRaw
      : seedRaw
        ? parseInt(String(seedRaw), 10) || undefined
        : undefined;

  // Image-to-image / image-edit references — BytePlus ModelArk
  // Seedream 4.5 + 5.0 expose TWO distinct ref modes that the API
  // distinguishes purely by field name:
  //
  //   `image`      (singular) → image-EDIT mode: the model uses the
  //                              ref as the canonical input and
  //                              preserves subject + composition,
  //                              regardless of prompt strength.
  //   `image_urls` (array)    → style/mood-BLEND mode: the model
  //                              draws loose inspiration only, and
  //                              with a short prompt it routinely
  //                              ignores the ref entirely.
  //
  // Verified 2026-05-15 against seedream-5-0-260128 +
  // seedream-4-5-251128 with the same ref and a short "reformat to
  // 9:16" prompt: `image` reliably reproduced the source subject;
  // `image_urls` returned an unrelated scene.
  //
  // The previous executor sent `{ image_urls: [url] }` for every
  // case based on a misread of the BytePlus spec — refs were
  // technically attached but the model behaved as if none were.
  // Switch back to `image` for the single-ref case (the dominant
  // canvas pattern: one ref_image edge or one @-mention); keep
  // `image_urls` for the multi-ref case where mood-blend is the
  // desired behaviour.
  //
  // The canvas writes wired ref-image edges into `ref_image`
  // (single URL when one connection, array when many). Standalone
  // tool calls historically used `image_url` (singular). Mention
  // path hands us `mention_image_urls`. Accept all three and
  // normalise to an array, capped at the API's 14-image limit.
  const collectRefUrls = (): string[] => {
    const acc: string[] = [];
    const push = (v: unknown) => {
      if (typeof v === "string" && v.length > 0) acc.push(v);
    };
    const refRaw = params.ref_image;
    if (Array.isArray(refRaw)) refRaw.forEach(push);
    else push(refRaw);
    push(params.image_url);
    push(params.image);
    if (Array.isArray(params.mention_image_urls)) {
      (params.mention_image_urls as unknown[]).forEach(push);
    }
    // Dedupe while preserving order — BytePlus indexes references
    // semantically ("Image 1", "Image 2" in the prompt), so the
    // order matters and we can't union into an unordered set.
    const seen = new Set<string>();
    const out: string[] = [];
    for (const u of acc) {
      if (seen.has(u)) continue;
      seen.add(u);
      out.push(u);
    }
    return out.slice(0, 14);
  };
  const refUrls = collectRefUrls();

  const negativePrompt =
    typeof params.negative_prompt === "string" ? params.negative_prompt : undefined;

  console.log(
    `[seedream] generate model=${entry.model} size=${size} seed=${seed ?? "auto"} ` +
      `refs=${refUrls.length}`,
  );

  const items = await generateSeedreamImage(
    {
      model: entry.model,
      prompt,
      size,
      response_format: "url",
      n: 1,
      // Force watermark off — BytePlus ships the international Ark
      // endpoint with watermarking enabled for Seedream calls that omit
      // this field, regardless of what the published default says.
      watermark: false,
      ...(seed !== undefined ? { seed } : {}),
      // Single ref → image-edit mode (`image`). Multi-ref → mood
      // blend (`image_urls`). See the comment block above
      // `collectRefUrls` for the field-name semantics.
      ...(refUrls.length === 1
        ? { image: refUrls[0] }
        : refUrls.length > 1
          ? { image_urls: refUrls }
          : {}),
      ...(negativePrompt ? { negative_prompt: negativePrompt } : {}),
    },
    apiKey,
  );

  const url = items[0]?.url;
  if (!url) {
    throw new Error("Seedream returned no URL in the first image item.");
  }

  // Mirror the BytePlus-hosted image into `ai-media` so the frontend
  // sees the same Supabase signed-URL shape every other image executor
  // (Banana / OpenAI / Freepik) produces. BytePlus output URLs are
  // short-lived CDN links; without mirroring, the result row points at
  // a URL that expires within hours AND `result_url` was left
  // undefined — which silently collapsed the downstream image-gen
  // node body to a thin line because neither the image branch nor the
  // empty placeholder matched.
  let publicUrl = url;
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`download HTTP ${res.status}`);
    if (!res.body) throw new Error("download response missing body");
    const contentType =
      res.headers.get("content-type")?.split(";")[0]?.trim() || "image/png";
    const ext =
      contentType.includes("webp") ? "webp" :
      contentType.includes("jpeg") || contentType.includes("jpg") ? "jpg" :
      contentType.includes("gif") ? "gif" :
      "png";
    const fileName = `pipeline/seedream_${Date.now()}.${ext}`;
    const { error: uploadError } = await supabase.storage
      .from("ai-media")
      .upload(fileName, res.body, { contentType, upsert: true });
    if (uploadError) throw uploadError;
    const { data: urlData, error: signError } = await supabase.storage
      .from("ai-media")
      .createSignedUrl(fileName, 60 * 60 * 24 * 7);
    if (!signError && urlData?.signedUrl) {
      publicUrl = urlData.signedUrl;
    } else {
      const { data: pubData } = supabase.storage
        .from("ai-media")
        .getPublicUrl(fileName);
      publicUrl = pubData.publicUrl;
    }
    console.log(`[seedream] mirrored image to storage path=${fileName}`);
  } catch (err) {
    console.warn(
      `[seedream] storage mirror failed, falling back to BytePlus URL: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }

  return {
    result_url: publicUrl,
    outputs: {
      output_image: publicUrl,
    },
    output_type: "image_url",
    provider_meta: {
      provider: "seedream",
      model: modelSlug,
      provider_model_id: entry.model,
      tier: entry.tier,
      size,
      revised_prompt: items[0]?.revised_prompt,
      reference_image_count: refUrls.length,
    },
  };
}
